name: .NET

on: [push]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 4.8.0     
    - name: Build with dotnet
      working-directory: ./src
      run: dotnet build 
    - name: Run Test
      working-directory: ./src
      run: dotnet test 
